AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Video Codec Framework - Simple Storage Resources'

Parameters:
  ProjectName:
    Type: String
    Default: ai-video-codec
    Description: Name of the project
    
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - production
    Description: Environment name
    
  AccountId:
    Type: String
    Description: AWS Account ID

Resources:
  # S3 Buckets
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-artifacts-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-artifacts'
        - Key: Environment
          Value: !Ref Environment
          
  VideosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-videos-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-videos'
        - Key: Environment
          Value: !Ref Environment
          
  ModelsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-models-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-models'
        - Key: Environment
          Value: !Ref Environment
          
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-reports-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-reports'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ArtifactsBucketName:
    Description: Artifacts S3 bucket name
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${ProjectName}-artifacts-bucket'
      
  VideosBucketName:
    Description: Videos S3 bucket name
    Value: !Ref VideosBucket
    Export:
      Name: !Sub '${ProjectName}-videos-bucket'
      
  ModelsBucketName:
    Description: Models S3 bucket name
    Value: !Ref ModelsBucket
    Export:
      Name: !Sub '${ProjectName}-models-bucket'
      
  ReportsBucketName:
    Description: Reports S3 bucket name
    Value: !Ref ReportsBucket
    Export:
      Name: !Sub '${ProjectName}-reports-bucket'
