AWSTemplateFormatVersion: '2010-09-09'
Description: 'AI Video Codec Framework - Storage Resources'

Parameters:
  ProjectName:
    Type: String
    Default: ai-video-codec
    Description: Name of the project
    
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - production
    Description: Environment name
    
  AccountId:
    Type: String
    Description: AWS Account ID

Resources:
  # S3 Buckets
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-artifacts-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-artifacts'
        - Key: Environment
          Value: !Ref Environment
        - Key: CostCategory
          Value: Storage
        - Key: Project
          Value: !Ref ProjectName
          
  VideosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-videos-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-videos'
        - Key: Environment
          Value: !Ref Environment
        - Key: CostCategory
          Value: Storage
        - Key: Project
          Value: !Ref ProjectName
          
  ModelsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-models-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-models'
        - Key: Environment
          Value: !Ref Environment
        - Key: CostCategory
          Value: Storage
        - Key: Project
          Value: !Ref ProjectName
          
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-reports-${AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-reports'
        - Key: Environment
          Value: !Ref Environment
        - Key: CostCategory
          Value: Storage
        - Key: Project
          Value: !Ref ProjectName
          
  # EFS File System
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      ThroughputMode: provisioned
      ProvisionedThroughputInMibps: 100
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: !Sub '${ProjectName}-efs'
        - Key: Environment
          Value: !Ref Environment
          
  # EFS Mount Targets
  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !ImportValue
        Fn::Sub: '${ProjectName}-private-subnet-1'
      SecurityGroups:
        - !Ref EFSSecurityGroup
        
  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !ImportValue
        Fn::Sub: '${ProjectName}-private-subnet-2'
      SecurityGroups:
        - !Ref EFSSecurityGroup
        
  # EFS Security Group
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-efs-sg'
      GroupDescription: Security group for EFS
      VpcId: !ImportValue
        Fn::Sub: '${ProjectName}-vpc-id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !ImportValue
            Fn::Sub: '${ProjectName}-orchestrator-sg'
          Description: NFS from orchestrator
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          SourceSecurityGroupId: !ImportValue
            Fn::Sub: '${ProjectName}-workers-sg'
          Description: NFS from workers
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-efs-sg'
          
  # KMS Keys for Encryption
  S3KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for S3 encryption
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow S3 to use the key
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-s3-key'
        - Key: Environment
          Value: !Ref Environment
          
  EFSKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for EFS encryption
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow EFS to use the key
            Effect: Allow
            Principal:
              Service: elasticfilesystem.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-efs-key'
        - Key: Environment
          Value: !Ref Environment
          
  # S3 Bucket Policies
  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${ArtifactsBucket.Arn}/*'
              - !GetAtt ArtifactsBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
                
  VideosBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref VideosBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${VideosBucket.Arn}/*'
              - !GetAtt VideosBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
                
  ModelsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ModelsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${ModelsBucket.Arn}/*'
              - !GetAtt ModelsBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
                
  ReportsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReportsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${ReportsBucket.Arn}/*'
              - !GetAtt ReportsBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

Outputs:
  ArtifactsBucketName:
    Description: Artifacts S3 bucket name
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${ProjectName}-artifacts-bucket'
      
  VideosBucketName:
    Description: Videos S3 bucket name
    Value: !Ref VideosBucket
    Export:
      Name: !Sub '${ProjectName}-videos-bucket'
      
  ModelsBucketName:
    Description: Models S3 bucket name
    Value: !Ref ModelsBucket
    Export:
      Name: !Sub '${ProjectName}-models-bucket'
      
  ReportsBucketName:
    Description: Reports S3 bucket name
    Value: !Ref ReportsBucket
    Export:
      Name: !Sub '${ProjectName}-reports-bucket'
      
  EFSFileSystemId:
    Description: EFS file system ID
    Value: !Ref EFSFileSystem
    Export:
      Name: !Sub '${ProjectName}-efs-id'
      
  EFSFileSystemDNS:
    Description: EFS file system DNS name
    Value: !GetAtt EFSFileSystem.DNSName
    Export:
      Name: !Sub '${ProjectName}-efs-dns'
      
  S3KMSKeyId:
    Description: S3 KMS key ID
    Value: !Ref S3KMSKey
    Export:
      Name: !Sub '${ProjectName}-s3-kms-key'
      
  EFSKMSKeyId:
    Description: EFS KMS key ID
    Value: !Ref EFSKMSKey
    Export:
      Name: !Sub '${ProjectName}-efs-kms-key'
